name: Buoncibo
favicon: null
layout_spectrum: 0.9247810593806207
typography_spectrum: 0.9459115341305733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.96831323672086
  lightness: 0.8443741651717573
  saturation: 0.08353927708230913
  rhythmicContrast: 0.21710364939644933
purpose: []
